version: '3'
# https://docs.docker.com/compose/compose-file/#/versioning

services:
    nginx:
        image: nginx:1.14
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ${WORKSPACE}:/var/www/html
        restart: always
        depends_on:
            - php
            - db
    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - ${WORKSPACE}:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        restart: always
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        expose:
            - 3306
        volumes:
            - ./database:/var/lib/mysql
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin:4.8
        depends_on:
            - db
        ports:
            - '3636:80'